### ISSUE TITLE
View All Appointments

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#20]
Staff can view a list of all upcoming appointments.

**Comment by BekahT** [comment]
- This is in the search pane before search criteria are applied.

**Comment by BekahT** [comment]
This should probably be sorted by date and within date by time so the table is displayed with appointments in ascending order (the one closest to now at the top).

**Comment by BekahT** [comment]
Show only upcoming appointments, not appointments in the past. However, appointments in the past should be displayed in the View Client window.

**Comment by BekahT** [comment]
Use SQL query that joins the appts table data with pets on pet id and clients on client id and returns pet name and client last name as well as all the appointment data. Similar to the one for the pets table, but with an additional join.

**Comment by BekahT** [comment]
I see in the Appointments table we are showing the Client's first and last names. Do we still want to search only on last name or whole client name? If we're showing client full name in appointments, can we do the same on pets, where we are currently only showing last name?

**Comment by BekahT** [comment]
- Implemented appointments search on client full name. Need to discuss if we want search on last name only. If so, we need a method in the Appointments class to get just the last name.
- Need to discuss whether to update the Pets table to include both first and last names like Appointments. I certainly think it's more useful to show both. Again, we'd need methods in the Pets class for full name (used by the table) and last name only (used by search).

**Comment by brease568** [comment]
The display inside the table was modeled after the GUI mockups. At this point, whatever is already implemented I say we leave the same - at least until we finish with the rest of the essential tickets. Right now the comments are really only on small items in the display. Changing anything will require changing back-end implementations. 

The search on full name or last name doesn't really matter because neither of those fields are unique in any of the tables. If its already implemented on full name I say leave it. If you want to change it then use the Scanner class and pull the client name from an Appointments object and take the second item. The client variable in Appointments is simple FIRST_NAME + " " + LAST_NAME.

As far the Pets table there is no point in changing one field to have first and last name but keeping the search as only last name when appointments is going to be first and last for search.

**Comment by cp-umuc** [comment]
Since we are displaying only upcoming appointments - what about taking time into account? It is currently 10:11 so should the 7:00 and 10:00 appointments not show up?
<img width="1027" alt="Screen Shot 2020-04-29 at 10 11 20 AM" src="https://user-images.githubusercontent.com/62041224/80606089-dd435800-8a01-11ea-88b5-a4cbc1ef055d.png">
I think it is okay if we leave them since it allows people to see what the day's schedule looks like but I just want to make sure we're on the same page.

**Comment by BekahT** [comment]
I think we may want to leave it so that all of today's appointments are shown, in case a client shows up late. Then the staff member would still be able to find their appointment. Otherwise, I can add an AND to the WHERE clause in the DB query to only return appointments later than now, including the time.

**Comment by cp-umuc** [comment]
I'm happy with leaving it as is (show all of today's appointments) if everyone else is.
