### ISSUE TITLE
View Client

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#5]
Staff can view an existing client’s current information.

**Comment by BekahT** [comment]
- During Phase I - only display contact information because search functionality is Phase II.

- Display associated pets and appointments along with client info.
- Same tables from pet and appointment search pages, but already filtered to just this client.
- If not enough real estate to have both tables, maybe use a toggle to view either pets or appointments table.

**Comment by BekahT** [comment]
- Make the overall Vet Portal window wider and make the panes with the tables wider as well. 
- When we do this, make sure the Appointments pane fits in its assigned area. Right now it's going over on the right side.

**Comment by BekahT** [comment]
> * Make the overall Vet Portal window wider and make the panes with the tables wider as well.
> * When we do this, make sure the Appointments pane fits in its assigned area. Right now it's going over on the right side.

- I was able to fix the Appts pane issue by making the search fields a bit less wide. However, we should still widen everything overall and things are getting crowded and on Mac they appear even more so. However, this is now addressed in #80 , so don't worry about it as part of this ticket, except to make sure this new window is wider than the ones we've previously made.

**Comment by cp-umuc** [comment]
Totally a nice to have comment and doesn't need to be done but can we center this information more on the page instead of having it all on the top and a bunch of white space?  If it is difficult don't worry about - just think it would look better.

<img width="506" alt="Screen Shot 2020-04-25 at 11 25 15 AM" src="https://user-images.githubusercontent.com/62041224/80283695-a7436280-86e7-11ea-86a0-5ab6baea8553.png">
