### ISSUE TITLE
Compare pet date of birth to current date

### ISSUE THREAD

**Issue by nour-d** [BekahT/VetApp#65]

**Comment by BekahT** [comment]
DOB cannot be after today's date. Pets must have been born in the past.
https://www.geeksforgeeks.org/compare-dates-in-java/

**Comment by cp-umuc** [comment]
What about today's date?  Do we want to be able to create a pet that was born today?  Right now I get an error if I try.  My preference is that the date can be today or earlier since the the test case says it can't be created in the future.
<img width="318" alt="Screen Shot 2020-04-23 at 10 07 20 PM" src="https://user-images.githubusercontent.com/62041224/80167775-3d27a200-85af-11ea-860f-de65e554938a.png">
